max_width = 120
tab_spaces = 4
use_small_heuristics = "Max"
indent_style = "Block"
wrap_comments = true
comment_width = 100
normalize_comments = true
fn_single_line = true
merge_imports = true
reorder_impl_items = true
type_punctuation_density = "Wide"
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
match_arm_blocks = false
force_multiline_blocks = true
fn_args_layout = "Compressed"
trailing_semicolon = false
trailing_comma = "Vertical"
edition = "2018"
use_field_init_shorthand = true
condense_wildcard_suffixes = true
report_todo = "Always"
report_fixme = "Always"
