condense_wildcard_suffixes = true
fn_args_layout = "Tall"
fn_single_line = true
force_multiline_blocks = true
format_strings = true
#indent_style = "Visual"
control_flow = "Visual"
function_arguments = "Visual"
function_calls = "Visual"
struct = "Visual"